# Packs Blender-exported model JSON into one gzip+base64 blob (src/models.js)
import json, glob, os, gzip, base64, struct
import numpy as np
root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
man = {}; chunks = []; off = 0
def add(arr):
    global off
    b = arr.tobytes(); pad = (-len(b)) % 4; b += b'\0' * pad
    o = off; chunks.append(b); off += len(b); return o
for f in sorted(glob.glob(os.path.join(root, 'models', '*.json'))):
    d = json.load(open(f)); name = d['name']
    P = np.array(d['pos'], np.float32).reshape(-1, 3); N = np.array(d['nor'], np.float32).reshape(-1, 3)
    C = np.array(d['col'], np.uint8).reshape(-1, 3); E = np.array(d['emi'], np.uint8); I = np.array(d['idx'], np.uint32)
    mn = P.min(0); mx = P.max(0); sc = np.maximum(mx - mn, 1e-6)
    Q = np.round((P - mn) / sc * 65535).astype(np.uint16)
    Nq = np.round(np.clip(N, -1, 1) * 127).astype(np.int8)
    if not (name.startswith('g_') or name.startswith('brute_') or name.startswith('boss_')):
        E = np.where(E < 250, (E.astype(np.float32) * 0.3).astype(np.uint8), E)   # soften infection veins; keep eyes at full glow
    CE = np.concatenate([C, E[:, None]], 1).astype(np.uint8)
    It = I.astype(np.uint16) if len(P) < 65536 else I
    man[name] = {'vc': len(P), 'ic': len(I), 'min': [float(x) for x in mn], 'sc': [float(x) for x in sc],
                 'p': add(Q), 'n': add(Nq), 'c': add(CE), 'i': add(It), 'i32': len(P) >= 65536}
blob = gzip.compress(b''.join(chunks), 9)
js = '/* generated by tools/pack_models.py from models/*.json (built in Blender by tools/make_models.py) */\n'
js += 'const MODEL_MANIFEST = ' + json.dumps(man, separators=(',', ':')) + ';\n'
js += 'const MODEL_BLOB = "' + base64.b64encode(blob).decode() + '";\n'
open(os.path.join(root, 'src', 'models.js'), 'w').write(js)
print('models', len(man), 'raw', off, 'gz', len(blob), 'js', len(js))
